#!/bin/bash

txtund=$(tput sgr 0 1)          # Underline
txtbld=$(tput bold)             # Bold
txtred=$(tput setaf 1)${txtbld} # Red
txtgreen=$(tput setaf 2)${txtbld} #  green
txtblue=$(tput setaf 4)${txtbld}  # blue
txtpink=$(tput setaf 5)${txtbld} #  pink
txtcyan=$(tput setaf 6)${txtbld} #  cyan
rst=$(tput sgr0)             # Reset

function bold(){ echo -e $txtbld "$@" $rst; }

function green() { echo -e $txtgreen "$1" $rst; }

function pink(){ echo $txtpink "$1" $rst; }

function cyan(){ echo -e $txtcyan "$1" $rst; }

function blue(){ echo -e $txtblue "$@" $rst; }

function red(){ echo -e $txtred "$@" $rst; }

function menu_multiple_choice() {
	echo
    echo "`gettext "Avaliable options:"`"
    echo
    for i in ${!required[@]}; do 
        printf "%3d%s) %s\n" $((i+1)) "${choices[i]:- }" "${required[i]}"
    done
    [[ "$msg" ]] && echo "$msg"; :
}

function menu_from_variable(){
echo
echo "`gettext " The following items were found."`"
blue "`gettext "Choose an number to confirm."`"
echo "`gettext " ctrl+c to quit"`" && echo
select CHOICE in $RESULT; do
    if [ -z "$CHOICE" ]; then
        bold "`gettext "Invalid choice!"`" && echo
        $FUNCNAME
    fi
    break
done
}

function menu_deselect(){
required=( $@ )
clear
choices=( `printf '+ %.0s' {1..100}` )
prompt="`gettext "Deselect an item (again to reselect, ENTER when ready):"`"
while menu_multiple_choice && read -n1 -rp "$prompt" num && [[ "$num" ]]; do
    [[ "$num" != *[![:digit:]]* ]] && (( num > 0 && num <= ${#required[@]} )) || {
        msg="Invalid option: $num"; clear; continue
    }
    ((num--)); msg=""
    [[ "${choices[num]}" ]] && choices[num]="" || choices[num]="+"
clear
done

msg=" nothing"
for i in ${!required[@]}; do
    #[[ "${choices[i]}" = "+" ]] && { FINALPKGS="${FINALPKGS} ${required[i]}"; msg=""; }
    if [ $frompackageGet ]; then
		[[ "${choices[i]}" = "+" ]] && NEWFINAL+=( `echo $FINALPKGS|tr ' ' '\n'|grep ${required[i]}` )
	elif [ $fromsystemDeps=0 ]; then
		[[ "${choices[i]}" = "+" ]] && NEWFINAL+=( ${required[i]} )
	else
		echo "Error at $FUNCNAME $LINENO: please notify brokenman"
	fi
done
FINALPKGS=${NEWFINAL[@]} && unset NEWFINAL
echo
}

function menu_deselect_plusten(){
required=( $@ )
clear
choices=( `printf '+ %.0s' {1..100}` )
prompt="`gettext "Type number and press enter to deselect an item (again to reselect, ENTER when ready):"`"
while menu_multiple_choice && read -rp "$prompt" num && [[ "$num" ]]; do
    [[ "$num" != *[![:digit:]]* ]] && (( num > 0 && num <= ${#required[@]} )) || {
        msg="Invalid option: $num"; clear; continue
    }
    ((num--)); msg=""
    [[ "${choices[num]}" ]] && choices[num]="" || choices[num]="+"
clear
done

msg=" nothing"
for i in ${!required[@]}; do 
    #[[ "${choices[i]}" ]] && { FINALPKGS="${FINALPKGS} ${required[i]}"; msg=""; }
    [[ "${choices[i]}" = "+" ]] && NEWFINAL+=( `echo $FINALPKGS|tr ' ' '\n'|grep ${required[i]}` )
done
FINALPKGS=${NEWFINAL[@]} && unset NEWFINAL
echo
}

function download() {
local url=$1
local file=${url##*/}

dloadInProgress=$url


if [ `grep "^PROXY=" $CONF` ]; then
	fPROXY=`awk -F'=' '/^PROXY=/{print$NF}' $CONF`
	export xPROXY=${fPROXY##*//}
	xPRE=`echo $fPROXY|cut -d':' -f1`
	[ -z $xPRE ] && xPRE=http
	export http_proxy=${xPRE}://${xPROXY}/
	export HTTP_PROXY=${xPRE}://${xPROXY}/
	if [ `grep "^PROXYUSER" $CONF` ]; then
		PXYUSER=`awk -F= '/^PROXYUSER/{print$NF}' $CONF`
		export http_proxy=${xPRE}://${PXYUSER}@${xPROXY}/
		export HTTP_PROXY=${xPRE}://${PXYUSER}@${xPROXY}/
	fi
	if [ `grep "^PROXYPASS" $CONF` ]; then
		PXYPASS=`awk -F= '/^PROXYPASS/{print$NF}' $CONF`
		export http_proxy=${xPRE}://${PXYUSER}:${PXYPASS}@${xPROXY}/
		export HTTP_PROXY=${xPRE}://${PXYUSER}:${PXYPASS}@${xPROXY}/
	fi
	echo "`gettext "Using proxy server:"`" $txtcyan " $xPROXY" $rst
fi

if [ "$DLOADER" = "curl" ]; then
    $DLOADER $2/$file $url
        else
    # Downloader is wget
    echo -n "Downloading: $file --> "
    $DLOADER $2/$file $url 2>&1 | grep --line-buffered "%" |sed -u -e "s,\.,,g" | awk '{printf("\b\b\b\b%4s", $2)}'
    echo -ne "\b\b\b\b"
    echo " DONE"
fi
unset dloadInProgress
}; export -f download

function help_check(){
[ `egrep "^-h$|^-help$|^--help$|^help$|\?" <<<$1` ] || [ -z $1 ] && return 0
}

function help_give(){
echo
echo -e $txtbld "Use: $1" $rst
echo " $2"
cleanup
}

silent_download(){ 
	wget --trust-server-names $1 -q -P $2
}; export -f silent_download
