#!/bin/bash

## Create elements for gtkdialog

## ======================================
## rbutCreate
## --------------------------------------
## Create a radio button item
## $1=variable
## $2=label
rbutCreate(){
echo '<label>'"$2"'</label>
		<variable>'$1'</variable>
	</radiobutton>'
}

## ======================================
## chkboxCreate
## --------------------------------------
## Create a radio button item
## $1=variable
## $2=label
chkboxCreate(){
echo '<label>'"$2"'</label>
		<variable>'$1'</variable>
	</checkbox>'
}

## ======================================
## butCreateStock
## --------------------------------------
## Create a button with stock icon
## $1=label
## $2=stock-icon
## $3=variable
butCreateStock() {
echo '<button>
	<label>'"$1"'</label>
	<input file stock="'$2'"></input>'
}

## ======================================
## menCreateItem
## --------------------------------------
## Create menu item for top menu
menCreateItem(){
echo '<menuitem icon="'$3'"><label>"'$1'"</label>
		<action>"'$2'"</action>'
}
